INSERT INTO Suppliers (SupplierID, Name, Address, City, Province, PostalCode)
VALUES (1, 'ABC Pharmaceuticals', '123 Main Street', 'New York', 'NY', '12345');

INSERT INTO Products (Name, Price, Recent_date_of_expiry)
VALUES ('Paracetamol', 10.99, '2022-12-31');

INSERT INTO PlaceOrder (SupplierID)
VALUES (1);

INSERT INTO Delivery_personals (License_number, FirstName, LastName, CityOfBirth, Vehicle_number)
VALUES ('DL123456', 'John', 'Smith', 'New York', 'ABC123');

INSERT INTO Customers (CustomerNumber, Name, AddressLine1, AddressLine2, City, StateProvince, Country, PostalCode)
VALUES (1, 'Jane Doe', '456 Elm Street', NULL, 'Los Angeles', 'CA', 'USA', '67890');

INSERT INTO Inventory (Inv_ID, Drug_Name, Quantity_on_Hand, Supplier_ID, Recent_date_of_expiry)
VALUES (1, 'Paracetamol', 100, 1, '2022-12-31');

INSERT INTO Doctors (FirstName, LastName, Specialty, Age)
VALUES ('John', 'Doe', 'Cardiology', 40);

INSERT INTO Prescription (Date_of_Prescription, Patient_ID, Doctor_ID, Drug_Name, Dosage)
VALUES ('2022-01-01', 1, 1, 'Paracetamol', '500mg');

INSERT INTO Orders (Prescription_ID, CustomerNumber, Date_of_order)
VALUES (1, 1, '2022-01-01');

INSERT INTO Ratings (Rating, OrderID, Supplier_ID)
VALUES (4, 1, 1);

INSERT INTO Delivery_log (Supplier_ID, Delivery_personal, Date_of_shipment, OrderID)
VALUES (1, 'DL123456', '2022-01-01', 1);



-- All the drugs specified by a particular DoctorID
SELECT Drug_Name FROM Prescription WHERE Doctor_ID = (SELECT DoctorID FROM Doctors WHERE FirstName = 'John' AND LastName = 'Doe');

-- All the orders placed by a particular customer
SELECT COUNT(*) FROM Orders WHERE CustomerNumber = (SELECT CustomerNumber FROM Customers WHERE Name = 'Jane Doe');

-- Update the quantity on hand of a particular drug after an order is placed
UPDATE Inventory SET Quantity_on_Hand = Quantity_on_Hand - 1 WHERE Inv_ID = (SELECT Prescription_ID FROM Orders WHERE OrderID = 101);

-- Average rating of a particular supplier
SELECT AVG(Rating) FROM Ratings WHERE Supplier_ID = (SELECT SupplierID FROM Suppliers WHERE Name = 'ABC Pharmaceuticals');

-- List of all the customers prescribed a particular drug
SELECT Name FROM Customers WHERE CustomerNumber IN (SELECT Patient_ID FROM Prescription WHERE Drug_Name = 'Paracetamol');

-- Revenue generated by a particular drug
SELECT SUM(Price) FROM Products WHERE ProductID IN (SELECT Prescription_No FROM Prescription WHERE Drug_Name = 'Paracetamol');

-- All the drugs that are about to go out of stock
SELECT Drug_Name FROM Inventory WHERE Quantity_on_Hand < 10;

-- All the doctors who have prescribed a particular drug more than 50 times
SELECT Doctor_ID FROM Prescription WHERE Drug_Name = 'Paracetamol' GROUP BY Doctor_ID HAVING COUNT(Prescription_No) > 50;

-- All the suppliers who have a rating less than 3
SELECT Supplier_ID FROM Ratings GROUP BY Supplier_ID HAVING MIN(Rating) >= 3;

-- Most frequently ordered drug
SELECT Drug_Name, COUNT(*) as Frequency FROM Prescription GROUP BY Drug_Name ORDER BY Frequency DESC LIMIT 1;
